#!/usr/bin/with-contenv bash

# Defines the EC2 instance ip on aws
EC2_IP="$(curl -s --connect-timeout 5 http://169.254.169.254/latest/meta-data/local-ipv4)"
if [ -n "${EC2_IP}" ]; then
  ZOO_IP=${EC2_IP}
else
  # Try to resolve the IP locally
  ZOO_IP="$(ip -o -4 addr list ${ZOO_BIND_INTERFACE:-eth0} | head -n1 | awk '{print $4}' | cut -d/ -f1)"
fi

echo -n "${ZOO_IP}" > /var/run/s6/container_environment/ZOO_IP

# Function to register the current zookeeper in Consul
register_zookeeper(){
  kv="service/${SERVICE_NAME}/servers/"

  # Register the existing myid in Consul
  if [ -f "$ZOO_DATA_DIR/myid" ] && [ -n "$CONSUL_HTTP_ADDR" ]; then
    zoo_id=$(cat $ZOO_DATA_DIR/myid)
    test -z ${zoo_id} && zoo_id=${ZOO_MY_ID:-1}
    echo "${zoo_id}" > "$ZOO_DATA_DIR/myid" && echo "Config '$ZOO_DATA_DIR/myid' created with Zookeeper ID '${zoo_id}'"
    consul kv put ${kv}${zoo_id} ${ZOO_IP}  && echo "ZooKeeper server '${ZOO_IP}' registered in Consul with ZooKeeper ID '${zoo_id}'" || echo "Failed to register ZooKeeper server '${ZOO_IP}' in Consul'"
    return 0
  fi

  # Generate a new myid and registered it in Consul and in the myid file
  if [ ! -f "$ZOO_DATA_DIR/myid" ] && [ -n "$CONSUL_HTTP_ADDR" ]; then

    # get a list of all existing keys into array
    for key in $(consul kv get -keys $kv); do
      keys+=(${key##*/})
    done

    # Find first available key in array
    for value in {1..255}; do
      if [[ ! " ${keys[@]} " =~ " ${value} " ]]; then
        zoo_id=${value}
        echo "${value}" > "$ZOO_DATA_DIR/myid" && echo "Config '$ZOO_DATA_DIR/myid' created with Zookeeper ID '${zoo_id}'"
        consul kv put ${kv}${zoo_id} ${ZOO_IP} && echo "ZooKeeper server '${ZOO_IP}' registered in Consul with ZooKeeper ID '${zoo_id}'" || echo "Failed to register ZooKeeper server '${ZOO_IP}' in Consul'"
        return 0
      fi
    done
    return 0
  fi

  if [ ! -f "$ZOO_DATA_DIR/myid" ]; then
    zoo_id=${ZOO_MY_ID:-1};
    echo "${zoo_id}" > "$ZOO_DATA_DIR/myid" && echo "Config '$ZOO_DATA_DIR/myid' created with Zookeeper ID '${zoo_id}'"
  else
    zoo_id=$(cat $ZOO_DATA_DIR/myid)
    test -z ${zoo_id} && { echo "Config '$ZOO_DATA_DIR/myid' is empty"; zoo_id=${ZOO_MY_ID:-1}; }
    echo "${zoo_id}" > "$ZOO_DATA_DIR/myid" && echo "Config '$ZOO_DATA_DIR/myid' created with Zookeeper ID '${zoo_id}'"
  fi
}

# Generate the config only if it doesn't exist
default_config(){
  if [ ! -f "$ZOO_CONF_DIR/zoo.cfg" ]; then
      CONFIG="$ZOO_CONF_DIR/zoo.cfg"

      echo "clientPort=$ZOO_PORT" >> "$CONFIG"
      echo "dataDir=$ZOO_DATA_DIR" >> "$CONFIG"
      echo "dataLogDir=$ZOO_DATA_LOG_DIR" >> "$CONFIG"

      echo "tickTime=$ZOO_TICK_TIME" >> "$CONFIG"
      echo "initLimit=$ZOO_INIT_LIMIT" >> "$CONFIG"
      echo "syncLimit=$ZOO_SYNC_LIMIT" >> "$CONFIG"

      for server in $ZOO_SERVERS; do
          echo "$server" >> "$CONFIG"
      done
  fi
}

# Create default config
default_config

# Register Zookeeper in Consul or just create the Zookeeper myid based on the variable ZOO_MY_ID
register_zookeeper

# Change directory permissions
chown -R "$ZOO_USER:$ZOO_USER" "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR"