#!/usr/bin/with-contenv bash

# FIXME remove as soon we are defining CONSUL_HTTP_ADDR in bandsintown/alpine images
export CONSUL_HTTP_ADDR=$CONSUL_ADDRESS

# Function to register the current zookeeper in Consul
register_zookeeper_id(){
  if [ ! -f "$ZOO_DATA_DIR/myid" ] ; then
    if [ -n "$CONSUL_HTTP_ADDR" ]; then
      kv="service/${SERVICE_NAME}/servers/"

      # Defines the EC2 instance ip on aws
      EC2_IP="$(curl -s --connect-timeout 5 http://169.254.169.254/latest/meta-data/local-ipv4)"
      if [ -n "${EC2_IP}" ]; then
        server_ip=${EC2_IP}
      else
        # Try to resolve the IP locally
        server_ip="$(ip -o -4 addr list ${ZOO_BIND_INTERFACE:-eth0} | head -n1 | awk '{print $4}' | cut -d/ -f1)"
      fi

      # check if a zookeeper id has been registered
      zoo_id=$(consul kv get ${kv}${server_ip}/id > /dev/null 2>&1)
      if [ "x" != "x${zoo_id}" ]; then
        echo "${zoo_id}" > "$ZOO_DATA_DIR/myid"
        echo "ZooKeeper server '${server_ip}' already registered in Consul with ZooKeeper ID '${zoo_id}'"
        echo "Config '$ZOO_DATA_DIR/myid' created with Zookeeper ID '${zoo_id}'"
        return 0
      fi

      # get a list of all existing keys into array
      for key in $(consul kv get -keys $kv); do
        keys+=($(consul kv get ${key}id))
      done

      # Find first available key in array
      for value in {1..255}; do
        if [[ ! " ${keys[@]} " =~ " ${value} " ]]; then
          consul kv put ${kv}${server_ip}/id ${value}
          echo "${value}" > "$ZOO_DATA_DIR/myid"
          echo "ZooKeeper server '${server_ip}' registered in Consul with ZooKeeper ID '${value}'"
          echo "Config '$ZOO_DATA_DIR/myid' created with Zookeeper ID '${value}'"
          return 0
        fi
      done
    else
      echo "${ZOO_MY_ID:-1}" > "$ZOO_DATA_DIR/myid"
    fi
  fi
}

# Generate the config only if it doesn't exist
default_config(){
  if [ ! -f "$ZOO_CONF_DIR/zoo.cfg" ]; then
      CONFIG="$ZOO_CONF_DIR/zoo.cfg"

      echo "clientPort=$ZOO_PORT" >> "$CONFIG"
      echo "dataDir=$ZOO_DATA_DIR" >> "$CONFIG"
      echo "dataLogDir=$ZOO_DATA_LOG_DIR" >> "$CONFIG"

      echo "tickTime=$ZOO_TICK_TIME" >> "$CONFIG"
      echo "initLimit=$ZOO_INIT_LIMIT" >> "$CONFIG"
      echo "syncLimit=$ZOO_SYNC_LIMIT" >> "$CONFIG"

      for server in $ZOO_SERVERS; do
          echo "$server" >> "$CONFIG"
      done
  fi
}

# Create default config
default_config

# Register Zookeeper ID
register_zookeeper_id

# Change directory permissions
chown -R "$ZOO_USER" "$ZOO_DATA_DIR" "$ZOO_DATA_LOG_DIR"